# Generated by Django 2.1.5 on 2020-01-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotationangles',
            name='document_type',
        ),
        migrations.AddField(
            model_name='rotationangles',
            name='error',
            field=models.TextField(default=None),
        ),
    ]
