# Generated by Django 2.1.5 on 2020-01-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_forms', '0003_auto_20200127_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationangles',
            name='errors',
            field=models.TextField(default=None, null=True),
        ),
    ]
